# Site settings
title: "Cantonese Opera"
description: "Experience rich Cantonese opera"
logo: mylogo.png
discus_shortname: CantoOpera
header-img: img/home-bg.jpg
email: midtpt@yahoo.com
url: https://midpt.github.io/cdrama2
search: true
share: true
comments: true

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: false

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name:   MK Cheong
  avatar: my_avatar.png
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    A colourful life

# Social networking links used in footer. Update and remove as you like.
twitter_username: midpt
facebook_username: midpt
github_username: midpt
deviantart_username: midpt
500px_username: midpt
flickr_username: midpt
instagram_username: midpt
  
 
# Internal nav
nav:
 writing: "source_url/writing/"
 gallery: "source_url/gallery/"
 about: "source_url/about/"


# Server
destination:      	 ./_site
port:             	 4000

# Build settings
highlighter:         pygments
markdown:           redcarpet
redcarpet:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
paginate: 5
paginate_path: "/writing/page:num/"
permalink: "/writing/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-xxxxxxxx-x
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         
